Шикунов Артем, группа 6311, лабораторная работа №4
itsecd/ptm-4 pull request #2
Opened 2023-11-20 23:17 UTC by artyEZ

В ходе данной лабораторной работы был написан класс FootballClub, чтобы затем имплементировать в него логгирование. с помощью библиотеки logging.

2023-11-21 13:38 UTC, alxmcs requested changes

2023-11-21 13:38 UTC, alxmcs commented on football_club.py
> +    def get_player_info(self, name: str):
Тут было бы неплохо залогировать факт того, что информация об игроке была запрошена (и насколько успешно)

2023-11-21 13:38 UTC, alxmcs commented on football_club.py
> +    def _is_financial_transaction_valid(self, amount: float) -> bool:
Раз поле с финансами клуба не является протектед, то можно логировать и его изменения

2023-11-21 15:37 UTC, alxmcs requested changes

2023-11-21 15:37 UTC, alxmcs commented on football_club.py
> +            self.logger.warning(f"No player named '{name}' found in the club.")
На 152 и 125 строках идентичные сообщения в лог порождаются разными методами. Гипотетический человек, которому придется по логам восстанавливать цепочку вызовов софта, чтобы найти баг, не скажет тебе спасибо. К сожалению, педагогическая этика запрещает мне конкретизировать, что он скажет. Но не спасибо.

2023-11-21 15:47 UTC, artyEZ commented on football_club.py
> +            self.logger.warning(f"No player named '{name}' found in the club.")
я бы тоже такому не был счастлив...

2023-11-22 07:58 UTC, alxmcs approved these changes

2023-11-22 07:58 UTC, closed without merging