6313-100503D Ненашев Дмитрий Михайлович Лаб.4
itsecd/ptm-4 pull request #50
Opened 2023-12-16 00:00 UTC by neygenius

Для выполнения задания взял код старой лабы: 
[github.com/neygenius/python/blob/lab1-var5/main.py](url)

_Логирование сделал довольно уродливым способом: одновременно и в консоль, и в файл, но с разными форматорами и уровнями логов_

2023-12-16 09:41 UTC, alxmcs requested changes

2023-12-16 09:41 UTC, alxmcs commented on main.py
> +console_logger.addHandler(console_handler)
Зачем заводить два логгера, если можно добавить в один логгер два хендлера? [пример](https://stackoverflow.com/questions/60473336/logging-to-file-and-console-with-different-handlers-and-formats)

2023-12-16 11:43 UTC, neygenius commented on main.py
> +console_logger.addHandler(console_handler)
Хотел сделать логгеры с разными уровнями, но сейчас понимаю, что смысла в этом нет

2023-12-17 07:30 UTC, alxmcs approved these changes
Зачтено

2023-12-17 07:32 UTC, closed without merging